name: Hello Agile

on:
  push:
    branches: [ dev ]      
  pull_request:
    branches: [ master ]      


jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello
        run: echo "Hello from GitHub Actions!"
